# Generated by Django 5.2.11 on 2026-02-12 00:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the tag (e.g., 'Castle', 'Church')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly version (auto-generated from name, e.g., 'castle')", max_length=100, unique=True)),
                ('icon', models.CharField(help_text="Emoji icon for visual representation (e.g., '🏰' for Castle)", max_length=10)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CulturalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name of the cultural object (e.g., 'Lviv Opera House')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the object (optional)')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (44.0 to 52.5 for Ukraine)', max_digits=9, validators=[django.core.validators.MinValueValidator(44.0, message='Latitude must be within Ukraine (44.0-52.5)'), django.core.validators.MaxValueValidator(52.5, message='Latitude must be within Ukraine (44.0-52.5)')])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (22.0 to 40.5 for Ukraine)', max_digits=9, validators=[django.core.validators.MinValueValidator(22.0, message='Longitude must be within Ukraine (22.0-40.5)'), django.core.validators.MaxValueValidator(40.5, message='Longitude must be within Ukraine (22.0-40.5)')])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('archived', 'Archived')], db_index=True, default='pending', help_text='Current moderation status', max_length=20)),
                ('wikipedia_url', models.URLField(blank=True, help_text='Link to Wikipedia article (optional)', null=True)),
                ('official_website', models.URLField(blank=True, help_text='Official website of the object (optional)', null=True)),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps link (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this object was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this object was last modified')),
                ('archived_at', models.DateTimeField(blank=True, help_text='When this object was archived (soft-deleted)', null=True)),
                ('author', models.ForeignKey(help_text='User who created this object', on_delete=django.db.models.deletion.CASCADE, related_name='cultural_objects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(help_text='Categories for this object (select 1-5 tags)', related_name='cultural_objects', to='objects.tag')),
            ],
            options={
                'verbose_name': 'Cultural Object',
                'verbose_name_plural': 'Cultural Objects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='objects_cul_status_d0b28a_idx'), models.Index(fields=['author'], name='objects_cul_author__8e5f42_idx'), models.Index(fields=['status', '-created_at'], name='objects_cul_status_17e078_idx')],
            },
        ),
    ]
