# Generated by Django 5.2.11 on 2026-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobject',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude coordinate (within Ukraine)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='culturalobject',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude coordinate (within Ukraine)', max_digits=9),
        ),
    ]
