# Generated by Django 5.2.11 on 2026-04-01 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_culturalobject_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalobject',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalobject',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalobject',
            name='object_type',
            field=models.CharField(choices=[('permanent', 'Постійний'), ('event', 'Подія')], db_index=True, default='permanent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='culturalobject',
            index=models.Index(fields=['object_type', 'event_end_date'], name='objects_cul_object__706663_idx'),
        ),
    ]
