# Generated by Django 5.2.11 on 2026-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_culturalobject_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobject',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturalobject',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
