# Generated by Django 5.2.11 on 2026-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_culturalobject_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('object', "Об'єкт"), ('event', 'Подія')], db_index=True, default='object', max_length=10),
        ),
    ]
