# Generated by Django 5.2.11 on 2026-04-01 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_tag_tag_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobject',
            name='object_type',
            field=models.CharField(choices=[('permanent', "Пам'ятка"), ('event', 'Подія')], db_index=True, default='permanent', max_length=20),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='objects.culturalobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cultural_object')},
            },
        ),
    ]
