# Generated by Django 5.2.11 on 2026-05-07 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_favoriteauthor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=255, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_author_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_cleanup_at', models.DateTimeField(blank=True, null=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='objects.culturalobject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_author_photo', 'order', 'created_at'],
                'indexes': [models.Index(fields=['cultural_object', 'status'], name='objects_obj_cultura_b74f06_idx'), models.Index(fields=['status', 'rejected_cleanup_at'], name='objects_obj_status_e82b6b_idx'), models.Index(fields=['uploaded_by'], name='objects_obj_uploade_e72c87_idx')],
            },
        ),
    ]
