# Generated by Django 5.2.11 on 2026-05-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_objectphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectphoto',
            options={'ordering': ['order', 'created_at']},
        ),
    ]
