# Generated by Django 5.2.11 on 2026-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='English translation; falls back to `name` when empty.', max_length=100),
        ),
    ]
