# Generated by Django 5.2.11 on 2026-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_tag_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5),
        ),
    ]
