# Generated by Django 5.2.11 on 2026-05-20 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_userpreference_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InaccuracyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('wrong_coords', 'Невірні координати'), ('wrong_name', 'Неточна назва'), ('wrong_description', 'Помилки в описі'), ('wrong_tags', 'Невірні теги'), ('duplicate', "Дублікат іншого об'єкта"), ('other', 'Інше')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('resolved', 'Підтверджено'), ('dismissed', 'Відхилено')], default='pending', max_length=10)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inaccuracy_reports', to='objects.culturalobject')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='objects_ina_status_88f8d4_idx'), models.Index(fields=['cultural_object', 'status'], name='objects_ina_cultura_32c19b_idx')],
            },
        ),
    ]
