# Generated by Django 5.2.11 on 2026-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_inaccuracyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('resolved', 'Вирішено'), ('dismissed', 'Відхилено')], default='pending', max_length=10),
        ),
    ]
