# Generated by Django 5.2.11 on 2026-05-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_alter_inaccuracyreport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalobject',
            options={'ordering': ['-created_at'], 'verbose_name': "Культурний об'єкт", 'verbose_name_plural': "Культурні об'єкти"},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обране', 'verbose_name_plural': 'Обране'},
        ),
        migrations.AlterModelOptions(
            name='favoriteauthor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Підписка на автора', 'verbose_name_plural': 'Підписки на авторів'},
        ),
        migrations.AlterModelOptions(
            name='inaccuracyreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Репорт про неточність', 'verbose_name_plural': 'Репорти про неточності'},
        ),
        migrations.AlterModelOptions(
            name='objectphoto',
            options={'ordering': ['order', 'created_at'], 'verbose_name': "Фото об'єкта", 'verbose_name_plural': "Фото об'єктів"},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
