# Generated by Django 5.2.11 on 2026-05-21 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_alter_culturalobject_options_alter_favorite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, help_text='Опційна планова дата', null=True)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='objects.culturalobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заплановане відвідування',
                'verbose_name_plural': 'Заплановані відвідування',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cultural_object')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateField(default=django.utils.timezone.now)),
                ('impression', models.TextField(blank=True, help_text='Враження від візиту', max_length=1000)),
                ('is_public', models.BooleanField(default=False, help_text='Чи показувати цей візит у публічному паспорті')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='objects.culturalobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Візит',
                'verbose_name_plural': 'Візити',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'visited_at'], name='objects_vis_user_id_f3b0d7_idx'), models.Index(fields=['cultural_object'], name='objects_vis_cultura_93b467_idx'), models.Index(fields=['is_public', 'user'], name='objects_vis_is_publ_b5b907_idx')],
                'unique_together': {('user', 'cultural_object')},
            },
        ),
    ]
