# Generated by Django 5.2.11 on 2026-05-21 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_plannedvisit_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
