# Generated by Django 5.2.11 on 2026-05-21 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_alter_visit_visited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На модерації'), ('approved', 'Опубліковано'), ('archived', 'В архіві')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover_photo', models.URLField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('copied_from', models.ForeignKey(blank=True, help_text='Якщо маршрут створений як копія', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='objects.route')),
                ('tags', models.ManyToManyField(blank=True, related_name='routes', to='objects.tag')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.culturalobject')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='objects.route')),
            ],
            options={
                'verbose_name': 'Зупинка маршруту',
                'verbose_name_plural': 'Зупинки маршруту',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status', '-created_at'], name='objects_rou_status_b9a085_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_featured', '-created_at'], name='objects_rou_is_feat_49bb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['author', 'status'], name='objects_rou_author__c2da03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'cultural_object')},
        ),
    ]
