# Generated by Django 5.2.11 on 2026-05-21 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0019_route_routestop_route_objects_rou_status_b9a085_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='route',
            name='objects_rou_status_b9a085_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='objects_rou_author__c2da03_idx',
        ),
        migrations.AddField(
            model_name='route',
            name='visibility',
            field=models.CharField(choices=[('private', 'Особистий'), ('public', 'Публічний')], default='private', help_text='Private — only author sees, no moderation. Public — visible to everyone after approval.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='objects_rou_visibil_61502d_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['author', 'visibility'], name='objects_rou_author__5a8cde_idx'),
        ),
    ]
