# Generated by Django 5.2.11 on 2026-05-21 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_remove_route_objects_rou_status_b9a085_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=255, unique=True)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], default='uk', max_length=2)),
                ('title', models.CharField(max_length=150)),
                ('narrator_name', models.CharField(blank=True, max_length=100)),
                ('copyright_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=20)),
                ('moderation_note', models.TextField(blank=True)),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='objects.culturalobject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудіо-нарратив',
                'verbose_name_plural': 'Аудіо-наративи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cultural_object', 'status'], name='objects_obj_cultura_530f82_idx'), models.Index(fields=['status', '-created_at'], name='objects_obj_status_afd133_idx'), models.Index(fields=['cultural_object', 'language', 'status'], name='objects_obj_cultura_da41e3_idx')],
            },
        ),
    ]
