# Generated by Django 5.2.11 on 2026-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_objectaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geometry_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_duration_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
