# Generated by Django 5.2.11 on 2026-05-23 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_route_geometry_updated_at_route_route_distance_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
