# Generated by Django 5.2.11 on 2026-05-23 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_alter_visit_visited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalobject',
            name='original_language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], default='uk', help_text='Мова, якою автор написав title/description.', max_length=5),
        ),
        migrations.AddField(
            model_name='route',
            name='original_language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], default='uk', help_text='Мова, якою автор написав title/description.', max_length=5),
        ),
        migrations.CreateModel(
            name='CulturalObjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено')], db_index=True, default='pending', max_length=10)),
                ('reviewer_note', models.TextField(blank=True, help_text='Нотатка адміна для рецензії/репортів.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.culturalobject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_object_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Переклад об'єкта",
                'verbose_name_plural': "Переклади об'єктів",
                'indexes': [models.Index(fields=['cultural_object', 'language', 'status'], name='objects_cul_cultura_de06b7_idx'), models.Index(fields=['status', '-created_at'], name='objects_cul_status_a64ed3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('cultural_object', 'language'), name='unique_approved_obj_translation_per_lang'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('cultural_object', 'language'), name='unique_pending_obj_translation_per_lang')],
            },
        ),
        migrations.CreateModel(
            name='RouteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено')], db_index=True, default='pending', max_length=10)),
                ('reviewer_note', models.TextField(blank=True, help_text='Нотатка адміна для рецензії/репортів.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.route')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_route_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Переклад маршруту',
                'verbose_name_plural': 'Переклади маршрутів',
                'indexes': [models.Index(fields=['route', 'language', 'status'], name='objects_rou_route_i_68be41_idx'), models.Index(fields=['status', '-created_at'], name='objects_rou_status_22b83b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('route', 'language'), name='unique_approved_route_translation_per_lang'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('route', 'language'), name='unique_pending_route_translation_per_lang')],
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.tag')),
            ],
            options={
                'verbose_name': 'Переклад тегу',
                'verbose_name_plural': 'Переклади тегів',
                'constraints': [models.UniqueConstraint(fields=('tag', 'language'), name='unique_tag_translation_per_lang')],
            },
        ),
    ]
