# Generated by Django 5.2.11 on 2026-05-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_culturalobject_original_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], default='uk', max_length=5),
        ),
    ]
