# Generated by Django 5.2.11 on 2026-05-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_alter_userpreference_language'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='culturalobjecttranslation',
            name='unique_pending_obj_translation_per_lang',
        ),
        migrations.RemoveConstraint(
            model_name='routetranslation',
            name='unique_pending_route_translation_per_lang',
        ),
    ]
