# Generated by Django 5.2.11 on 2026-05-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0026_remove_culturalobjecttranslation_unique_pending_obj_translation_per_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=10),
        ),
    ]
