# Generated by Django 5.2.11 on 2026-05-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('objects', '0027_alter_culturalobjecttranslation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inaccuracyreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Репорт', 'verbose_name_plural': 'Репорти'},
        ),
        migrations.RemoveIndex(
            model_name='inaccuracyreport',
            name='objects_ina_cultura_32c19b_idx',
        ),
        migrations.AddField(
            model_name='inaccuracyreport',
            name='content_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_on_my_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inaccuracyreport',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inaccuracyreport',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='cultural_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inaccuracy_reports', to='objects.culturalobject'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='reason_type',
            field=models.CharField(choices=[('wrong_coords', 'Невірні координати'), ('wrong_name', 'Неточна назва'), ('wrong_description', 'Помилки в описі'), ('wrong_tags', 'Невірні теги'), ('duplicate', 'Дублікат'), ('spam', 'Спам'), ('offensive', 'Образливий вміст'), ('copyright', 'Порушення авторських прав'), ('broken_media', 'Пошкоджене медіа'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='inaccuracyreport',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='objects_ina_content_f49433_idx'),
        ),
        migrations.AddIndex(
            model_name='inaccuracyreport',
            index=models.Index(fields=['content_owner', 'status'], name='objects_ina_content_2f4575_idx'),
        ),
    ]
