# Generated by Django 5.2.11 on 2026-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_report_polymorphic_step3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='note',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
