# Generated by Django 5.2.11 on 2026-05-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0031_report_note_2000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='cultural_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.culturalobject', verbose_name="Культурний об'єкт"),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='reviewer_note',
            field=models.TextField(blank=True, help_text='Нотатка адміна для рецензії/репортів.', verbose_name='Нотатка рецензента'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_object_translations', to=settings.AUTH_USER_MODEL, verbose_name='Запропонував'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='Відповідь адміністратора'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='content_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_on_my_content', to=settings.AUTH_USER_MODEL, verbose_name='Власник контенту'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='note',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Деталі'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='reason_type',
            field=models.CharField(choices=[('wrong_coords', 'Невірні координати'), ('wrong_name', 'Неточна назва'), ('wrong_description', 'Помилки в описі'), ('wrong_tags', 'Невірні теги'), ('duplicate', 'Дублікат'), ('spam', 'Спам'), ('offensive', 'Образливий вміст'), ('copyright', 'Порушення авторських прав'), ('broken_media', 'Пошкоджене медіа'), ('other', 'Інше')], max_length=20, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Репортер'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опрацьовано'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Опрацював'),
        ),
        migrations.AlterField(
            model_name='inaccuracyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('resolved', 'Вирішено'), ('dismissed', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='reviewer_note',
            field=models.TextField(blank=True, help_text='Нотатка адміна для рецензії/репортів.', verbose_name='Нотатка рецензента'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_route_translations', to=settings.AUTH_USER_MODEL, verbose_name='Запропонував'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('pl', 'Polski'), ('de', 'Deutsch')], max_length=5, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
