# Generated by Django 5.2.11 on 2026-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0033_seed_tag_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobjecttranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='objectaudio',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='routetranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Затверджено'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
