# Generated by Django 5.2.11 on 2026-05-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0035_backfill_tag_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
    ]
