# Generated by Django 5.2.11 on 2026-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0036_drop_tag_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='impression',
            field=models.TextField(blank=True, help_text='Враження від візиту', max_length=2000),
        ),
    ]
