# Generated by Django 5.2.11 on 2026-05-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0037_alter_visit_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectphoto',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Причина відхилення (показується автору фото).'),
        ),
    ]
