# Generated by Django 5.2.11 on 2026-05-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0038_objectphoto_moderation_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='cover_photo',
        ),
    ]
