# Generated by Django 5.2.11 on 2026-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0039_remove_route_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobject',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Затверджено'), ('archived', 'Архівовано')], db_index=True, default='pending', help_text='Current moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено'), ('archived', 'В архіві')], db_index=True, default='pending', max_length=20),
        ),
    ]
