# Generated by Django 5.2.11 on 2026-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0040_alter_culturalobject_status_alter_objectphoto_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectaudio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аудіонаратив', 'verbose_name_plural': 'Аудіонаративи'},
        ),
    ]
